<!DOCTYPE html>
<html>
<head>
    <title>Sortir Game</title>
    <link href='https://fonts.googleapis.com/css?family=Exo+2:400,200,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href="assets/css/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="assets/css/styles.css" rel="stylesheet" type="text/css">
</head>
<body ng-app="gameApp">
    <div class="container">
        <div class="logo_block">
            <div class="logo_name">SortirGame</div>
            <div class="login_block">
                <div class="user">
                    <div class="user_name">Max Shishkov</div>    
                    <div class="user_face"><img src="assets/images/test.jpg"></div>
                </div>
                <div class="user_score">Score: 1250</div>
            </div>
        </div>
        <div class="everything">
            <div ui-view></div>
        </div>
    </div>
    
    <script src="assets/js/jquery-1.12.4.min.js"></script>
    <script src="assets/js/jquery-ui.js"></script>
    <script src="assets/js/angular.min.js"></script>
    <script src="assets/js/angular-resource.js"></script>
    <script src="assets/js/angular-ui-router.js"></script>
    <script src="assets/js/slider.js"></script>
    
    <!-- App -->
    <script src="game.js"></script>

    <!-- Services -->
    <script src="Game/Users/usersService.js"></script>

    <!-- Controllers -->
    <script src="Game/gameController.js"></script>
    <script src="Game/menuController.js"></script>
    <script src="Game/Start/startController.js"></script>
    <script src="Game/Users/usersController.js"></script>

</body>
</html>